language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer -v fix . --dry-run --config-file ./.php_cs

notifications:
  email:
  - and-rey2@yandex.ru

branches:
  only:
    - dev