language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer require --dev

install:
  - travis_retry composer install


script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat --config=behat.yml  --format=progress
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run --config-file ./.php_cs

after_script:
  - ./vendor/bin/phpcov merge --clover .reports/clover.xml .reports/coverage
  - ./vendor/bin/coveralls -v  --quiet --config .coveralls.yml

notifications:
  email:
  - and-rey2@yandex.ru

branches:
  only:
    - dev